<?php

namespace Mvc\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    /**
     * Grab all messages, with users infos
     */
    public function findAllWithUsers()
    {
        $qb = $this->createQueryBuilder('m');

        $qb->join('m.user', 'u')
            ->addSelect('u')
            ->orderBy('m.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

}
