security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Mvc\UserBundle\Entity\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations: 1


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: Mvc\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main: 
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: sign_in
                check_path: login_check
            logout:
                path: sign_out
                target: /

    access_control:
      #  - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
