home:
    pattern:  /
    defaults: { _controller: MvcBlogBundle:Message:index }

new_message:
    pattern: /new-message
    defaults: { _controller: MvcBlogBundle:Message:new }

delete_message:
    pattern: /delete-message/{id}
    defaults: { _controller: MvcBlogBundle:Message:delete }
    requirements: 
        id: \d+
